#!/bin/bash
#

cd /usr/local/calenergy/
mydir=$PWD

##

caliso() {
    /usr/local/calenergy/bin/caliso.sh
    sleep 5
}

renewable() {
    /usr/local/calenergy/bin/renewable.sh
    sleep 5
}
insert() {
    /usr/local/calenergy/bin/insert.sh
    sleep 5
}

caliso
renewable
insert
